/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import ControladorBD.QuerysAlumnos;
import ControladorBD.QuerysCronograma;
import ControladorBD.QuerysInstructores;
import ControladorBD.QuerysProgramas;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Frank
 */
public class AlertaEliminar extends javax.swing.JFrame {

     List<Integer> listaEliminar = new ArrayList<>();
     private String tipo = "";
    /**
     * Creates new form AlertaEliminar
     */
    public AlertaEliminar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void setlistaEliminar(List<Integer> selectedIds,String tipo){
        this.listaEliminar = selectedIds;
        this.tipo = tipo;
    }
    public void ciclo(String a){
        for (int i = 0; i < listaEliminar.size(); i++) {
             int numero = listaEliminar.get(i);
             if(a.equals("Instructor")){
                 QuerysInstructores ElimI = new QuerysInstructores();
                 ElimI.eliminarInstructor(numero);
             }else if(a.equals("Alumno")){
                 QuerysAlumnos ElimA = new QuerysAlumnos();
                 ElimA.eliminarAlumno(numero);
             }else if(a.equals("Programa")){
                 QuerysProgramas ElimP = new QuerysProgramas();
                 ElimP.eliminarPrograma(numero);
             }else if(a.equals("Cronograma")){
                 QuerysCronograma ElimC = new QuerysCronograma();
                 ElimC.eliminarCronograma(numero);} 
        }
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Mensaje = new javax.swing.JLabel();
        SiPanel = new javax.swing.JPanel();
        SiBoton = new javax.swing.JLabel();
        NoPanel = new javax.swing.JPanel();
        NoBoton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(255, 51, 51));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mensaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Mensaje.setForeground(new java.awt.Color(255, 255, 255));
        Mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mensaje.setText("¿Estas seguro que quieres eliminar?");
        PanelPrincipal.add(Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, -1));

        SiPanel.setBackground(new java.awt.Color(80, 200, 120));

        SiBoton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SiBoton.setForeground(new java.awt.Color(255, 255, 255));
        SiBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SiBoton.setText("SI");
        SiBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SiBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SiBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SiBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SiPanelLayout = new javax.swing.GroupLayout(SiPanel);
        SiPanel.setLayout(SiPanelLayout);
        SiPanelLayout.setHorizontalGroup(
            SiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SiBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        SiPanelLayout.setVerticalGroup(
            SiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SiBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelPrincipal.add(SiPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        NoPanel.setBackground(new java.awt.Color(80, 200, 120));

        NoBoton.setBackground(new java.awt.Color(255, 255, 255));
        NoBoton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NoBoton.setForeground(new java.awt.Color(255, 255, 255));
        NoBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoBoton.setText("NO");
        NoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NoBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NoBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout NoPanelLayout = new javax.swing.GroupLayout(NoPanel);
        NoPanel.setLayout(NoPanelLayout);
        NoPanelLayout.setHorizontalGroup(
            NoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NoPanelLayout.setVerticalGroup(
            NoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelPrincipal.add(NoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SiBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SiBotonMouseClicked
       ciclo(tipo);
       dispose();
    }//GEN-LAST:event_SiBotonMouseClicked

    private void NoBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoBotonMouseClicked
        dispose();
    }//GEN-LAST:event_NoBotonMouseClicked

    private void SiBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SiBotonMouseEntered
        SiPanel.setBackground(new Color (32,67,114));
    }//GEN-LAST:event_SiBotonMouseEntered

    private void SiBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SiBotonMouseExited
        SiPanel.setBackground(new Color (80,200,120));
    }//GEN-LAST:event_SiBotonMouseExited

    private void NoBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoBotonMouseEntered
        NoPanel.setBackground(new Color (32,67,114));
    }//GEN-LAST:event_NoBotonMouseEntered

    private void NoBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoBotonMouseExited
        NoPanel.setBackground(new Color (80,200,120));
    }//GEN-LAST:event_NoBotonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlertaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlertaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlertaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlertaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlertaEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mensaje;
    private javax.swing.JLabel NoBoton;
    private javax.swing.JPanel NoPanel;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel SiBoton;
    private javax.swing.JPanel SiPanel;
    // End of variables declaration//GEN-END:variables
}
