/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import ControladorBD.ConexionBD;
import ControladorBD.QuerysProgramas;
import java.awt.Color;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Frank
 */
public class AñadirPrograma extends javax.swing.JFrame {

    /**
     * Creates new form A
     */
    public AñadirPrograma() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        FechaInicio = new javax.swing.JLabel();
        FechaFin = new javax.swing.JLabel();
        Horario = new javax.swing.JLabel();
        MaximoInscritos = new javax.swing.JLabel();
        Costo = new javax.swing.JLabel();
        Instructor = new javax.swing.JLabel();
        Detalles = new javax.swing.JLabel();
        InstructorComboBox = new javax.swing.JComboBox<>();
        CancelarPanel = new javax.swing.JPanel();
        CancelarBoton = new javax.swing.JLabel();
        GuardarPanel = new javax.swing.JPanel();
        GuardarBoton = new javax.swing.JLabel();
        NombreCampo = new javax.swing.JTextField();
        FechaInicioCampo = new javax.swing.JTextField();
        MaximoInscritosCampo = new javax.swing.JTextField();
        HorarioCampo = new javax.swing.JTextField();
        CostoCampo = new javax.swing.JTextField();
        FechaFinCampo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DetallesCampo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(209, 209, 209));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(1050, 650));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Titulo.setText("Añadir un programa");
        PanelPrincipal.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 530, 60));

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Nombre.setText("Nombre:");
        PanelPrincipal.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 180, 50));

        FechaInicio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FechaInicio.setText("Fecha de inicio:");
        PanelPrincipal.add(FechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 180, 50));

        FechaFin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FechaFin.setText("Fecha fin:");
        PanelPrincipal.add(FechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 180, 50));

        Horario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Horario.setText("Horario:");
        PanelPrincipal.add(Horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 180, 50));

        MaximoInscritos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MaximoInscritos.setText("Nº max inscritos:");
        PanelPrincipal.add(MaximoInscritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 200, 50));

        Costo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Costo.setText("Costo:");
        PanelPrincipal.add(Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 200, 50));

        Instructor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Instructor.setText("Instructor");
        PanelPrincipal.add(Instructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 200, 50));

        Detalles.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Detalles.setText("Detalles:");
        PanelPrincipal.add(Detalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 100, 50));

        InstructorComboBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        InstructorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructorComboBoxActionPerformed(evt);
            }
        });
        PanelPrincipal.add(InstructorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 210, 30));

        CancelarPanel.setBackground(new java.awt.Color(80, 200, 120));

        CancelarBoton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CancelarBoton.setForeground(new java.awt.Color(255, 255, 255));
        CancelarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancelarBoton.setText("Cancelar");
        CancelarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CancelarPanelLayout = new javax.swing.GroupLayout(CancelarPanel);
        CancelarPanel.setLayout(CancelarPanelLayout);
        CancelarPanelLayout.setHorizontalGroup(
            CancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CancelarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        CancelarPanelLayout.setVerticalGroup(
            CancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CancelarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelPrincipal.add(CancelarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 150, 50));

        GuardarPanel.setBackground(new java.awt.Color(80, 200, 120));

        GuardarBoton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GuardarBoton.setForeground(new java.awt.Color(255, 255, 255));
        GuardarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GuardarBoton.setText("Guardar");
        GuardarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuardarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuardarBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout GuardarPanelLayout = new javax.swing.GroupLayout(GuardarPanel);
        GuardarPanel.setLayout(GuardarPanelLayout);
        GuardarPanelLayout.setHorizontalGroup(
            GuardarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuardarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GuardarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        GuardarPanelLayout.setVerticalGroup(
            GuardarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuardarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GuardarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelPrincipal.add(GuardarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, -1, -1));

        NombreCampo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NombreCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreCampoKeyTyped(evt);
            }
        });
        PanelPrincipal.add(NombreCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 210, 30));

        FechaInicioCampo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PanelPrincipal.add(FechaInicioCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 210, 30));

        MaximoInscritosCampo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaximoInscritosCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MaximoInscritosCampoKeyTyped(evt);
            }
        });
        PanelPrincipal.add(MaximoInscritosCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 210, 30));

        HorarioCampo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PanelPrincipal.add(HorarioCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 210, 30));

        CostoCampo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CostoCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CostoCampoKeyTyped(evt);
            }
        });
        PanelPrincipal.add(CostoCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 210, 30));

        FechaFinCampo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FechaFinCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FechaFinCampoKeyTyped(evt);
            }
        });
        PanelPrincipal.add(FechaFinCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 210, 30));

        DetallesCampo.setColumns(20);
        DetallesCampo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DetallesCampo.setRows(5);
        jScrollPane1.setViewportView(DetallesCampo);

        PanelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 550, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InstructorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstructorComboBoxActionPerformed

    private void CancelarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBotonMouseClicked
        dispose();
        
    }//GEN-LAST:event_CancelarBotonMouseClicked

    private void CancelarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBotonMouseEntered
        CancelarPanel.setBackground(new Color (32,67,114));
    }//GEN-LAST:event_CancelarBotonMouseEntered

    private void CancelarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBotonMouseExited
        CancelarPanel.setBackground(new Color (80,200,120));
    }//GEN-LAST:event_CancelarBotonMouseExited

    private void GuardarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarPanelMouseEntered

    private void GuardarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarBotonMouseEntered
        GuardarPanel.setBackground(new Color (32,67,114));
        
    }//GEN-LAST:event_GuardarBotonMouseEntered

    private void GuardarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarBotonMouseExited
        GuardarPanel.setBackground(new Color (80,200,120));
    }//GEN-LAST:event_GuardarBotonMouseExited

    private void GuardarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarBotonMouseClicked
        // TODO add your handling code here:
        // Obtener el ID_Instructor a partir del nombre seleccionado en el JComboBox
    int ID_INSTRUCTOR = obtenerIDInstructor();

    // Verificar que se haya obtenido un ID_Instructor válido
    if (ID_INSTRUCTOR != -1) {
        // Crear instancia de la clase que maneja la inserción del programa
        QuerysProgramas qp = new QuerysProgramas();

        // Llamar al método insertarPrograma con todos los parámetros, incluyendo el ID_INSTRUCTOR obtenido
        qp.insertarPrograma(NombreCampo.getText(), 
                            FechaInicioCampo.getText(), 
                            FechaFinCampo.getText(),
                            Integer.parseInt(CostoCampo.getText().trim()), 
                            HorarioCampo.getText(), 
                            DetallesCampo.getText(),
                            Integer.parseInt(MaximoInscritosCampo.getText().trim()), 
                            ID_INSTRUCTOR);
        // Cerrar la ventana actual
        dispose();
    } else {
        // Si el ID_Instructor no es válido, mostrar un mensaje de error
        //JOptionPane.showMessageDialog(null, "❌ Instructor no encontrado. Verifique el nombre.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_GuardarBotonMouseClicked

    private void GuardarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarPanelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_GuardarPanelMouseClicked

    private void GuardarBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarBotonMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_GuardarBotonMousePressed

    private void GuardarBotonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarBotonMouseReleased
        // TODO add your handling code here:
  
    }//GEN-LAST:event_GuardarBotonMouseReleased

    private void GuardarBotonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GuardarBotonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarBotonKeyPressed

    private void NombreCampoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreCampoKeyTyped
        // TODO add your handling code here:
        Validaciones.SoloTexto(NombreCampo, "kun fu, Karte, Jujitsu, etc.");
    }//GEN-LAST:event_NombreCampoKeyTyped

    private void MaximoInscritosCampoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaximoInscritosCampoKeyTyped
        // TODO add your handling code here:
        Validaciones.SoloNumeros(MaximoInscritosCampo, "20, 50, etc.");
    }//GEN-LAST:event_MaximoInscritosCampoKeyTyped

    private void CostoCampoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CostoCampoKeyTyped
        // TODO add your handling code here:
        Validaciones.SoloNumeros(CostoCampo, "250, 500, 1000, etc.");
    }//GEN-LAST:event_CostoCampoKeyTyped

    private void FechaFinCampoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FechaFinCampoKeyTyped
        // TODO add your handling code here:
        Validaciones.validarFecha(evt, FechaFinCampo);
    }//GEN-LAST:event_FechaFinCampoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirPrograma().setVisible(true);
            }
        });
    }
public void cargarInstructoresEnComboBox() {
    // Crear el ComboBox si no está creado aún
    InstructorComboBox.removeAllItems(); // Limpiar el ComboBox antes de agregar nuevos elementos

    // Consulta SQL para obtener los nombres completos de los instructores
    String sql = "SELECT CONCAT(persona.nombre, ' ', persona.apellido_paterno, ' ', persona.apellido_materno) AS nombre_completo " +
                 "FROM instructor " +
                 "INNER JOIN persona ON instructor.ID_Persona = persona.ID_Persona";

    ConexionBD conexionBD = new ConexionBD();
    conexionBD.conectar();
    Connection conn = conexionBD.getConexion();

    try (java.sql.Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(sql)) {
        while (rs.next()) {
            String nombreCompleto = rs.getString("nombre_completo");
            InstructorComboBox.addItem(nombreCompleto); // Añadir el nombre completo al ComboBox
        }
    } catch (SQLException e) {
        e.printStackTrace();
    } finally {
        conexionBD.desconectar();
    }
}

private int obtenerIDInstructor() {
    // Obtener el nombre completo seleccionado en el JComboBox
    String nombreCompleto = (String) InstructorComboBox.getSelectedItem();
    
    // Separar el nombre completo en partes (suponiendo que el formato es "Nombre Apellido1 Apellido2")
    String[] partes = nombreCompleto.split(" ");
    
    // Solo tomamos el primer nombre
    String nombre = partes[0];  // Nombre sin apellidos
    
    // Consulta SQL para obtener el ID_Instructor
    String sql = "SELECT i.ID_Instructor FROM persona p " +
                 "INNER JOIN instructor i ON p.ID_Persona = i.ID_Persona " +
                 "WHERE p.nombre = ?";  // Suponemos que 'nombre' es único, si no, agregar más condiciones
    
    ConexionBD conexionBD = new ConexionBD();
    conexionBD.conectar();
    Connection conn = conexionBD.getConexion();
    
    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
        stmt.setString(1, nombre);  // Establecer el nombre para la consulta
        
        ResultSet rs = stmt.executeQuery();
        if (rs.next()) {
            // Devolver el ID_Instructor si se encuentra
            return rs.getInt("ID_Instructor");
        } else {
            System.out.println("❌ No se encontró el instructor con nombre: " + nombre);
            return -1;  // Retorna un valor negativo si no se encuentra
        }
    } catch (SQLException e) {
        System.out.println("❌ Error al obtener el ID_Instructor.");
        e.printStackTrace();
        return -1;
    } finally {
        conexionBD.desconectar();
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CancelarBoton;
    private javax.swing.JPanel CancelarPanel;
    private javax.swing.JLabel Costo;
    private javax.swing.JTextField CostoCampo;
    private javax.swing.JLabel Detalles;
    private javax.swing.JTextArea DetallesCampo;
    private javax.swing.JLabel FechaFin;
    private javax.swing.JTextField FechaFinCampo;
    private javax.swing.JLabel FechaInicio;
    private javax.swing.JTextField FechaInicioCampo;
    private javax.swing.JLabel GuardarBoton;
    private javax.swing.JPanel GuardarPanel;
    private javax.swing.JLabel Horario;
    private javax.swing.JTextField HorarioCampo;
    private javax.swing.JLabel Instructor;
    private javax.swing.JComboBox<String> InstructorComboBox;
    private javax.swing.JLabel MaximoInscritos;
    private javax.swing.JTextField MaximoInscritosCampo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreCampo;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
