/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.Color;

/**
 *
 * @author Frank
 */
public class AñadirPrueba extends javax.swing.JFrame {

    /**
     * Creates new form AñadirPrueba
     */
    public AñadirPrueba() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Lugar = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        Programa = new javax.swing.JLabel();
        LugarCampo = new java.awt.TextField();
        FechaCampo = new java.awt.TextField();
        HoraCampo = new java.awt.TextField();
        TipoComboBox = new javax.swing.JComboBox<>();
        CancelarPanel = new javax.swing.JPanel();
        CancelarBoton = new javax.swing.JLabel();
        GuardarPanel = new javax.swing.JPanel();
        GuardarBoton = new javax.swing.JLabel();
        ProgramaComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(209, 209, 209));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(1050, 650));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Titulo.setText("Registrar prueba");
        PanelPrincipal.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 530, 60));

        Lugar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Lugar.setText("Lugar:");
        PanelPrincipal.add(Lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 80, 50));

        Fecha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Fecha.setText("Fecha:");
        PanelPrincipal.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 80, 50));

        Tipo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tipo.setText("Tipo:");
        PanelPrincipal.add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 80, 50));

        Hora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Hora.setText("Hora:");
        PanelPrincipal.add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 120, 50));

        Programa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Programa.setText("Programa:");
        PanelPrincipal.add(Programa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 120, 50));

        LugarCampo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LugarCampo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LugarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugarCampoActionPerformed(evt);
            }
        });
        LugarCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LugarCampoKeyTyped(evt);
            }
        });
        PanelPrincipal.add(LugarCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 580, 30));

        FechaCampo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        FechaCampo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FechaCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaCampoActionPerformed(evt);
            }
        });
        FechaCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FechaCampoKeyTyped(evt);
            }
        });
        PanelPrincipal.add(FechaCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 210, 30));

        HoraCampo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        HoraCampo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HoraCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraCampoActionPerformed(evt);
            }
        });
        HoraCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HoraCampoKeyTyped(evt);
            }
        });
        PanelPrincipal.add(HoraCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 210, 30));

        TipoComboBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Practica", "Examen" }));
        TipoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoComboBoxActionPerformed(evt);
            }
        });
        PanelPrincipal.add(TipoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 210, 30));

        CancelarPanel.setBackground(new java.awt.Color(80, 200, 120));

        CancelarBoton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CancelarBoton.setForeground(new java.awt.Color(255, 255, 255));
        CancelarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancelarBoton.setText("Cancelar");
        CancelarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CancelarPanelLayout = new javax.swing.GroupLayout(CancelarPanel);
        CancelarPanel.setLayout(CancelarPanelLayout);
        CancelarPanelLayout.setHorizontalGroup(
            CancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CancelarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        CancelarPanelLayout.setVerticalGroup(
            CancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CancelarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelPrincipal.add(CancelarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 150, 50));

        GuardarPanel.setBackground(new java.awt.Color(80, 200, 120));
        GuardarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuardarPanelMouseEntered(evt);
            }
        });

        GuardarBoton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GuardarBoton.setForeground(new java.awt.Color(255, 255, 255));
        GuardarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GuardarBoton.setText("Guardar");
        GuardarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuardarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuardarBotonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GuardarBotonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                GuardarBotonMouseReleased(evt);
            }
        });
        GuardarBoton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GuardarBotonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout GuardarPanelLayout = new javax.swing.GroupLayout(GuardarPanel);
        GuardarPanel.setLayout(GuardarPanelLayout);
        GuardarPanelLayout.setHorizontalGroup(
            GuardarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuardarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GuardarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        GuardarPanelLayout.setVerticalGroup(
            GuardarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuardarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GuardarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelPrincipal.add(GuardarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, -1, -1));

        ProgramaComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProgramaComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramaComboBox1ActionPerformed(evt);
            }
        });
        PanelPrincipal.add(ProgramaComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LugarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugarCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LugarCampoActionPerformed

    private void LugarCampoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LugarCampoKeyTyped
        // TODO add your handling code here:
        Validaciones.soloLetras(evt);
    }//GEN-LAST:event_LugarCampoKeyTyped

    private void FechaCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaCampoActionPerformed

    private void FechaCampoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FechaCampoKeyTyped
        // TODO add your handling code here:
        Validaciones.validarFecha(evt, FechaCampo);
    }//GEN-LAST:event_FechaCampoKeyTyped

    private void HoraCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraCampoActionPerformed

    private void HoraCampoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HoraCampoKeyTyped
        // TODO add your handling code here:
        Validaciones.soloNumeros(evt);
    }//GEN-LAST:event_HoraCampoKeyTyped

    private void TipoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoComboBoxActionPerformed

    private void CancelarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBotonMouseClicked
        dispose();

    }//GEN-LAST:event_CancelarBotonMouseClicked

    private void CancelarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBotonMouseEntered
        CancelarPanel.setBackground(new Color (32,67,114));
    }//GEN-LAST:event_CancelarBotonMouseEntered

    private void CancelarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBotonMouseExited
        CancelarPanel.setBackground(new Color (80,200,120));
    }//GEN-LAST:event_CancelarBotonMouseExited

    private void GuardarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarBotonMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_GuardarBotonMouseClicked

    private void GuardarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarBotonMouseEntered
        GuardarPanel.setBackground(new Color (32,67,114));

    }//GEN-LAST:event_GuardarBotonMouseEntered

    private void GuardarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarBotonMouseExited
        GuardarPanel.setBackground(new Color (80,200,120));
    }//GEN-LAST:event_GuardarBotonMouseExited

    private void GuardarBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarBotonMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_GuardarBotonMousePressed

    private void GuardarBotonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarBotonMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_GuardarBotonMouseReleased

    private void GuardarBotonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GuardarBotonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarBotonKeyPressed

    private void GuardarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarPanelMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_GuardarPanelMouseClicked

    private void GuardarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarPanelMouseEntered

    private void ProgramaComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramaComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgramaComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CancelarBoton;
    private javax.swing.JPanel CancelarPanel;
    private javax.swing.JLabel Fecha;
    private java.awt.TextField FechaCampo;
    private javax.swing.JLabel GuardarBoton;
    private javax.swing.JPanel GuardarPanel;
    private javax.swing.JLabel Hora;
    private java.awt.TextField HoraCampo;
    private javax.swing.JLabel Lugar;
    private java.awt.TextField LugarCampo;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel Programa;
    public javax.swing.JComboBox<String> ProgramaComboBox1;
    private javax.swing.JLabel Tipo;
    public javax.swing.JComboBox<String> TipoComboBox;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
