/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.awt.Color;
import ControladorBD.ConexionBD;
import ControladorBD.QuerysCronograma;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.Timer;
import java.util.TimerTask;
import javax.sound.midi.Soundbank;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author jhona
 */
public class CronogramaBackground extends javax.swing.JPanel {

    /**
     * Creates new form ProgramasBackground
     */
    public CronogramaBackground() {
        initComponents();
        //iniciarActualizacionAutomatica();
        //this.actualizarTablaCronogramas()
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EliminarPanel = new javax.swing.JPanel();
        EliminarBoton = new javax.swing.JLabel();
        EditarPanel = new javax.swing.JPanel();
        EditarBoton = new javax.swing.JLabel();
        AgregarPanel = new javax.swing.JPanel();
        AgregarBoton = new javax.swing.JLabel();
        Intructorestxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCronogramas = new javax.swing.JTable();
        BuscadorAlumnos = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        busqueda = new javax.swing.JButton();

        setBackground(new java.awt.Color(209, 209, 209));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EliminarPanel.setBackground(new java.awt.Color(80, 200, 120));

        EliminarBoton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EliminarBoton.setForeground(new java.awt.Color(255, 255, 255));
        EliminarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EliminarBoton.setText("ELIMINAR");
        EliminarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EliminarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EliminarPanelLayout = new javax.swing.GroupLayout(EliminarPanel);
        EliminarPanel.setLayout(EliminarPanelLayout);
        EliminarPanelLayout.setHorizontalGroup(
            EliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EliminarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        EliminarPanelLayout.setVerticalGroup(
            EliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EliminarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(EliminarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 615, -1, -1));

        EditarPanel.setBackground(new java.awt.Color(80, 200, 120));
        EditarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarPanelMouseClicked(evt);
            }
        });

        EditarBoton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EditarBoton.setForeground(new java.awt.Color(255, 255, 255));
        EditarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditarBoton.setText("EDITAR");
        EditarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EditarPanelLayout = new javax.swing.GroupLayout(EditarPanel);
        EditarPanel.setLayout(EditarPanelLayout);
        EditarPanelLayout.setHorizontalGroup(
            EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        EditarPanelLayout.setVerticalGroup(
            EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(EditarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 615, -1, -1));

        AgregarPanel.setBackground(new java.awt.Color(80, 200, 120));

        AgregarBoton.setBackground(new java.awt.Color(255, 255, 255));
        AgregarBoton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AgregarBoton.setForeground(new java.awt.Color(255, 255, 255));
        AgregarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgregarBoton.setText("AGREGAR");
        AgregarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout AgregarPanelLayout = new javax.swing.GroupLayout(AgregarPanel);
        AgregarPanel.setLayout(AgregarPanelLayout);
        AgregarPanelLayout.setHorizontalGroup(
            AgregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        AgregarPanelLayout.setVerticalGroup(
            AgregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(AgregarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 615, -1, -1));

        Intructorestxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Intructorestxt.setForeground(new java.awt.Color(55, 67, 66));
        Intructorestxt.setText("Cronogramas");
        add(Intructorestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 240, 60));

        TablaCronogramas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Lugar", "Fecha", "Hora", "Tipo", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaCronogramas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 135, 788, 430));

        BuscadorAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add(BuscadorAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 250, 50));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Practica", "Examen" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 130, 30));

        busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/simbolo-de-interfaz-cuadrada-de-busqueda-de-datos-con-una-herramienta-de-lupa (1).png"))); // NOI18N
        busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busquedaMouseClicked(evt);
            }
        });
        add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 50, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarBotonMouseClicked
        AlertaEliminar ventanaEmergente = new AlertaEliminar();
        ventanaEmergente.setVisible(true);
        ventanaEmergente.setlistaEliminar(getSelectedIds(TablaCronogramas),"Cronograma");
    }//GEN-LAST:event_EliminarBotonMouseClicked

    public List<Integer> getSelectedIds(JTable table) {
        List<Integer> selectedIds = new ArrayList<>();
        for (int i = 0; i < table.getRowCount(); i++) {
            Boolean isChecked = (Boolean) table.getValueAt(i, 5); // Columna de checkbox
            if (Boolean.TRUE.equals(isChecked)) {
                Integer id = (Integer) table.getValueAt(i, 0); // Columna de ID
                selectedIds.add(id);
            }
        }
        return selectedIds;
    }
    
    private void EditarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarBotonMouseClicked
        
            List<Integer> selectedIds = getSelectedIds(TablaCronogramas);

    if (selectedIds.isEmpty()) { 
        JOptionPane.showMessageDialog(null, "⚠️ No has seleccionado ningún registro.", "Error", JOptionPane.WARNING_MESSAGE);
    } else if (selectedIds.size() > 1) { 
        JOptionPane.showMessageDialog(null, "⚠️ Solo puedes editar un registro a la vez.", "Error", JOptionPane.WARNING_MESSAGE);
    } else { 
        int ID_Cronograma = selectedIds.get(0);      
        EditarPrueba ap = new EditarPrueba(ID_Cronograma);  
        ap.setVisible(true);
    }
    }//GEN-LAST:event_EditarBotonMouseClicked

    private void AgregarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarBotonMouseClicked
        AñadirPrueba ap = new AñadirPrueba();
        ap.setVisible(true);
        ap.cargarProgramasEnComboBox();
    }//GEN-LAST:event_AgregarBotonMouseClicked

    private void AgregarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarBotonMouseEntered
         AgregarPanel.setBackground(new Color (32,67,114));
    }//GEN-LAST:event_AgregarBotonMouseEntered

    private void AgregarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarBotonMouseExited
         AgregarPanel.setBackground(new Color (80,200,120));
    }//GEN-LAST:event_AgregarBotonMouseExited

    private void EditarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarBotonMouseEntered
        EditarPanel.setBackground(new Color (32,67,114));
    }//GEN-LAST:event_EditarBotonMouseEntered

    private void EditarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarBotonMouseExited
        EditarPanel.setBackground(new Color (80,200,120));
    }//GEN-LAST:event_EditarBotonMouseExited

    private void EliminarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarBotonMouseEntered
        EliminarPanel.setBackground(new Color (32,67,114));
    }//GEN-LAST:event_EliminarBotonMouseEntered

    private void EliminarBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarBotonMouseExited
        EliminarPanel.setBackground(new Color (80,200,120));
    }//GEN-LAST:event_EliminarBotonMouseExited

    private void EditarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarPanelMouseClicked
        // TODO add your handling code here:
    List<Integer> selectedIds = getSelectedIds(TablaCronogramas);

    if (selectedIds.isEmpty()) { 
        JOptionPane.showMessageDialog(null, "⚠️ No has seleccionado ningún registro.", "Error", JOptionPane.WARNING_MESSAGE);
    } else if (selectedIds.size() > 1) { 
        JOptionPane.showMessageDialog(null, "⚠️ Solo puedes editar un registro a la vez.", "Error", JOptionPane.WARNING_MESSAGE);
    } else { 
        int ID_Cronograma = selectedIds.get(0);      
        EditarPrueba ap = new EditarPrueba(ID_Cronograma);  
        ap.setVisible(true);
    }
    }//GEN-LAST:event_EditarPanelMouseClicked

        private void iniciarActualizacionAutomatica() {
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                actualizarTablaCronogramas();
            }
        }, 0, 3000);
    }
public void actualizarTablaCronogramas() {
    System.out.println("🔄 Actualizando tabla de cronogramas...");

    ConexionBD conexionBD = new ConexionBD();
    conexionBD.conectar();
    Connection conn = conexionBD.getConexion();

    if (conn == null) {
        System.out.println("❌ Error: No se pudo establecer conexión con la BD.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) TablaCronogramas.getModel();
    model.setRowCount(0); // Limpiar la tabla antes de llenarla
    System.out.println("🗑️ Tabla vaciada.");

    String sql = "SELECT ID_Cronograma, Lugar, Fecha, Hora, Tipo FROM cronograma";

    List<Object[]> datosCronograma = new ArrayList<>();

    try (PreparedStatement stmt = conn.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {

        System.out.println("📊 Consulta ejecutada.");

        int contador = 0;
        while (rs.next()) {
            int idCronograma = rs.getInt("ID_Cronograma");
            String lugar = rs.getString("Lugar");
            String fecha = rs.getString("Fecha");
            String hora = rs.getString("Hora");
            String tipo = rs.getString("Tipo");

            // Última columna es "null" porque no la usaremos
            Object[] fila = { idCronograma, lugar, fecha, hora, tipo, null };
            datosCronograma.add(fila);
            contador++;
        }

        System.out.println("✅ Total de registros obtenidos: " + contador);

    } catch (SQLException e) {
        System.out.println("❌ Error al ejecutar la consulta.");
        e.printStackTrace();
    } finally {
        conexionBD.desconectar();
        System.out.println("🔌 Desconectado de la BD.");
    }

    // Llenar la tabla con los datos obtenidos
    for (Object[] cronograma : datosCronograma) {
        model.addRow(cronograma);
    }
}

    private void busquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busquedaMouseClicked
        // TODO add your handling code here:
        Validaciones.filtrarTabla(TablaCronogramas, BuscadorAlumnos);
    }//GEN-LAST:event_busquedaMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarBoton;
    private javax.swing.JPanel AgregarPanel;
    private javax.swing.JTextField BuscadorAlumnos;
    private javax.swing.JLabel EditarBoton;
    private javax.swing.JPanel EditarPanel;
    private javax.swing.JLabel EliminarBoton;
    private javax.swing.JPanel EliminarPanel;
    private javax.swing.JLabel Intructorestxt;
    private javax.swing.JTable TablaCronogramas;
    private javax.swing.JButton busqueda;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
